<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUdlyfPJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUdlyfPJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUdlyfPJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUdlyfPJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUdlyfPJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'UdlyfPJ',
    'container.build_id' => '5a1c0fff',
    'container.build_time' => 1709725640,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUdlyfPJ');
