<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app__homepage' => [[], ['_controller' => 'App\\Controller\\Controller::homepage'], [], [['text', '/']], [], [], []],
    'productos_anadir' => [[], ['_controller' => 'App\\Controller\\Controller::productosAnadir'], [], [['text', '/anadir']], [], [], []],
    'productos_buscar' => [[], ['_controller' => 'App\\Controller\\Controller::productosBuscar'], [], [['text', '/buscar']], [], [], []],
    'producto_mostrar' => [[], ['_controller' => 'App\\Controller\\Controller::productosBuscadoMostrar'], [], [['text', '/buscard']], [], [], []],
    'actualizar_producto' => [[], ['_controller' => 'App\\Controller\\Controller::modificarProducto'], [], [['text', '/actualizar']], [], [], []],
    'eliminar_producto' => [[], ['_controller' => 'App\\Controller\\Controller::mostrarProductos'], [], [['text', '/eliminar']], [], [], []],
    'App\Controller\Controller::homepage' => [[], ['_controller' => 'App\\Controller\\Controller::homepage'], [], [['text', '/']], [], [], []],
    'App\Controller\Controller::productosAnadir' => [[], ['_controller' => 'App\\Controller\\Controller::productosAnadir'], [], [['text', '/anadir']], [], [], []],
    'App\Controller\Controller::productosBuscar' => [[], ['_controller' => 'App\\Controller\\Controller::productosBuscar'], [], [['text', '/buscar']], [], [], []],
    'App\Controller\Controller::productosBuscadoMostrar' => [[], ['_controller' => 'App\\Controller\\Controller::productosBuscadoMostrar'], [], [['text', '/buscard']], [], [], []],
    'App\Controller\Controller::modificarProducto' => [[], ['_controller' => 'App\\Controller\\Controller::modificarProducto'], [], [['text', '/actualizar']], [], [], []],
    'App\Controller\Controller::mostrarProductos' => [[], ['_controller' => 'App\\Controller\\Controller::mostrarProductos'], [], [['text', '/eliminar']], [], [], []],
];
